### ISSUE TITLE
 studi-list/main.c returning pointer to local stack variable (segvault)

### ISSUE THREAD

**Issue by Servostar** [PlexSheep/studi-list#5]
Variable `s` created locally (in line 37) [-Wreturn-stack-address].

```C
student* inputStudent(){
    char tmpnum[50];
    student s;
```
and returned pointer to local variable (change to heap allocation):
```C
student* inputStudent(){
    char tmpnum[50];
    student *s = (student*) malloc(sizeof(student));
```

**Comment by PlexSheep** [comment]
If you `malloc()` a new pointer, does that mean it is not stored on the functions stack?
That would be helpful for the implementation for linked lists aswell.

Will fix.

**Comment by Servostar** [comment]
function such as `malloc()` or `calloc()` generally request the OS to give a process some memory from the heap. This happens dynamically. Stack allocations in C require the compiler to know the exact size at compilation time (although dynamic stack allocation are possible to do but not easy to do because it could invalidate the content of registers `rsp` or even `rip` and thus crash the program). Also the stack can only grow or shrink at the top. not inbetween. meaning `realloc()` wouldn't work on the stack cuz of its static and strict layout nature. 
Additionally the functions stack and everything on it gets (will get at some point) destroyed when returned.

**Comment by PlexSheep** [comment]
I'm working on it. Created a new branch

**Comment by PlexSheep** [comment]
Nevermind, it seems like that issue was already fixed with commit https://github.com/PlexSheep/studi-list/commit/085719e844cfbf25912ff94babfda9501df512b7 . Closing branch and issue.
